/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#dae2fd",
        "outline": "#777587",
        "on-error": "#ffffff",
        "on-background": "#0b1c30",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#eaf1ff",
        "tertiary": "#005338",
        "surface-bright": "#f8f9ff",
        "on-secondary": "#ffffff",
        "secondary-container": "#dae2fd",
        "outline-variant": "#c7c4d8",
        "surface-container-lowest": "#ffffff",
        "background": "#f8f9ff",
        "on-primary-fixed-variant": "#3323cc",
        "surface-dim": "#cbdbf5",
        "primary": "#3525cd",
        "on-error-container": "#93000a",
        "surface-tint": "#4d44e3",
        "on-secondary-fixed-variant": "#3f465c",
        "tertiary-fixed": "#6ffbbe",
        "primary-fixed-dim": "#c3c0ff",
        "surface-container": "#e5eeff",
        "on-primary-container": "#dad7ff",
        "surface": "#f8f9ff",
        "on-surface": "#0b1c30",
        "on-tertiary-container": "#67f4b7",
        "primary-container": "#4f46e5",
        "inverse-surface": "#213145",
        "surface-variant": "#d3e4fe",
        "secondary-fixed-dim": "#bec6e0",
        "on-tertiary-fixed-variant": "#005236",
        "error": "#ba1a1a",
        "surface-container-high": "#dce9ff",
        "on-primary": "#ffffff",
        "tertiary-container": "#006e4b",
        "on-surface-variant": "#464555",
        "secondary": "#565e74",
        "surface-container-highest": "#d3e4fe",
        "surface-container-low": "#eff4ff",
        "tertiary-fixed-dim": "#4edea3",
        "error-container": "#ffdad6",
        "on-secondary-container": "#5c647a",
        "on-secondary-fixed": "#131b2e",
        "inverse-primary": "#c3c0ff",
        "primary-fixed": "#e2dfff",
        "on-primary-fixed": "#0f0069",
        "on-tertiary-fixed": "#002113"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-desktop": "40px",
        "unit": "8px",
        "gutter": "24px",
        "container-max": "1280px",
        "margin-mobile": "16px"
      },
      fontFamily: {
        "headline-md": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "display-lg-mobile": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}